// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftnetManager.Modules.Shared.Database;

#nullable disable

namespace SoftnetManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationStatus")
                        .HasColumnType("int");

                    b.Property<int?>("ZoneID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ZoneID");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Line1 = "126 GANEGODA",
                            Line2 = "ARUKWATTA PADUKKA",
                            LocationStatus = 2,
                            ZoneID = 10
                        });
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AddressID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AddressID");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddressID = 1,
                            Name = "Padukka Branch"
                        });
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityName = "Colombo",
                            ProvinceID = 1
                        },
                        new
                        {
                            Id = 2,
                            CityName = "Gampaha",
                            ProvinceID = 1
                        },
                        new
                        {
                            Id = 3,
                            CityName = "Kalutara",
                            ProvinceID = 1
                        },
                        new
                        {
                            Id = 4,
                            CityName = "Kandy",
                            ProvinceID = 2
                        },
                        new
                        {
                            Id = 5,
                            CityName = "Nuwara Eliya",
                            ProvinceID = 2
                        },
                        new
                        {
                            Id = 6,
                            CityName = "Galle",
                            ProvinceID = 3
                        },
                        new
                        {
                            Id = 7,
                            CityName = "Matara",
                            ProvinceID = 3
                        });
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientURL")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = "Client1",
                            ClientURL = "https://client1.com",
                            Name = "Client Application 1"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = "Client2",
                            ClientURL = "https://client2.com",
                            Name = "Client Application 2"
                        });
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.Designation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DesignationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Designations");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DesignationName = "Feild Development Officer",
                            ShortName = "FDO"
                        },
                        new
                        {
                            ID = 2,
                            DesignationName = "Customer Relationship Officer",
                            ShortName = "CRO"
                        },
                        new
                        {
                            ID = 3,
                            DesignationName = "Branch Manager",
                            ShortName = "BM"
                        });
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.Gender", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            GenderName = "Male"
                        },
                        new
                        {
                            ID = 2,
                            GenderName = "FeMale"
                        },
                        new
                        {
                            ID = 3,
                            GenderName = "Other"
                        });
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.MaritialStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MaritialStatuses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Status = "Married"
                        },
                        new
                        {
                            ID = 2,
                            Status = "UnMarried"
                        },
                        new
                        {
                            ID = 3,
                            Status = "Widow"
                        });
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "View products",
                            Name = "Product.Read"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Create products",
                            Name = "Product.Create"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Update products",
                            Name = "Product.Update"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Delete products",
                            Name = "Product.Delete"
                        },
                        new
                        {
                            Id = 5,
                            Description = "View users",
                            Name = "User.Read"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Update users",
                            Name = "User.Update"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Delete users",
                            Name = "User.Delete"
                        });
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.Province", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ProvinceName = "Western"
                        },
                        new
                        {
                            ID = 2,
                            ProvinceName = "Central"
                        },
                        new
                        {
                            ID = 3,
                            ProvinceName = "Southern"
                        });
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UserId");

                    b.HasIndex("ClientId", "UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Admin Role",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = " Editor Role",
                            Name = "Editor"
                        },
                        new
                        {
                            Id = 3,
                            Description = "User Role",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.Salutation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("SalutationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Salutations");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            SalutationName = "Mr."
                        },
                        new
                        {
                            ID = 2,
                            SalutationName = "Mrs."
                        },
                        new
                        {
                            ID = 3,
                            SalutationName = "Ms."
                        },
                        new
                        {
                            ID = 4,
                            SalutationName = "Doc."
                        },
                        new
                        {
                            ID = 5,
                            SalutationName = "Ven."
                        },
                        new
                        {
                            ID = 6,
                            SalutationName = "Prof."
                        });
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.SigningKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrivateKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SigningKeys");
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserProfileID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserProfileID");

                    b.HasIndex(new[] { "Email" }, "IX_User_Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.UserProfile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AddressID")
                        .HasColumnType("int");

                    b.Property<int?>("BranchID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeactivatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("DesignationID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("GenderID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaritialStatusID")
                        .HasColumnType("int");

                    b.Property<string>("Nic")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SalutationID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AddressID");

                    b.HasIndex("BranchID");

                    b.HasIndex("DesignationID");

                    b.HasIndex("GenderID");

                    b.HasIndex("MaritialStatusID");

                    b.HasIndex("Nic")
                        .IsUnique()
                        .HasFilter("[Nic] IS NOT NULL");

                    b.HasIndex("SalutationID");

                    b.HasIndex(new[] { "Nic" }, "IX_User_Nic")
                        .IsUnique()
                        .HasFilter("[Nic] IS NOT NULL");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.Zone", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CityID = 1,
                            ZoneName = "Colombo 01 (Fort)"
                        },
                        new
                        {
                            ID = 2,
                            CityID = 1,
                            ZoneName = "Colombo 03 (Kollupitiya)"
                        },
                        new
                        {
                            ID = 3,
                            CityID = 1,
                            ZoneName = "Colombo 07 (Cinnamon Gardens)"
                        },
                        new
                        {
                            ID = 4,
                            CityID = 2,
                            ZoneName = "Ja-Ela"
                        },
                        new
                        {
                            ID = 5,
                            CityID = 2,
                            ZoneName = "Negombo"
                        },
                        new
                        {
                            ID = 6,
                            CityID = 4,
                            ZoneName = "Peradeniya"
                        },
                        new
                        {
                            ID = 7,
                            CityID = 4,
                            ZoneName = "Katugastota"
                        },
                        new
                        {
                            ID = 8,
                            CityID = 6,
                            ZoneName = "Galle Fort"
                        },
                        new
                        {
                            ID = 9,
                            CityID = 6,
                            ZoneName = "Karapitiya"
                        },
                        new
                        {
                            ID = 10,
                            CityID = 1,
                            ZoneName = "Sitawaka"
                        });
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.Address", b =>
                {
                    b.HasOne("SoftnetManager.Modules.Identity.Domain.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneID");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.Branch", b =>
                {
                    b.HasOne("SoftnetManager.Modules.Identity.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.City", b =>
                {
                    b.HasOne("SoftnetManager.Modules.Identity.Domain.Entities.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SoftnetManager.Modules.Identity.Domain.Entities.Client", "Client")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftnetManager.Modules.Identity.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("SoftnetManager.Modules.Identity.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftnetManager.Modules.Identity.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.User", b =>
                {
                    b.HasOne("SoftnetManager.Modules.Identity.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("SoftnetManager.Modules.Identity.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SoftnetManager.Modules.Identity.Domain.Entities.Branch", "Branch")
                        .WithMany("users")
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SoftnetManager.Modules.Identity.Domain.Entities.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SoftnetManager.Modules.Identity.Domain.Entities.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SoftnetManager.Modules.Identity.Domain.Entities.MaritialStatus", "MaritialStatus")
                        .WithMany()
                        .HasForeignKey("MaritialStatusID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SoftnetManager.Modules.Identity.Domain.Entities.Salutation", "Salutation")
                        .WithMany()
                        .HasForeignKey("SalutationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Address");

                    b.Navigation("Branch");

                    b.Navigation("Designation");

                    b.Navigation("Gender");

                    b.Navigation("MaritialStatus");

                    b.Navigation("Salutation");
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("SoftnetManager.Modules.Identity.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftnetManager.Modules.Identity.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.Zone", b =>
                {
                    b.HasOne("SoftnetManager.Modules.Identity.Domain.Entities.City", "City")
                        .WithMany("Zones")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.Branch", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.City", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.Client", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.Province", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SoftnetManager.Modules.Identity.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
